### ISSUE TITLE
The type initializer for 'Inner`3' threw an exception

### ISSUE THREAD

**Issue by IKende** [Tornhoof/SpanJson#120]
```
The type initializer for 'Inner`3' threw an exception.@   at lambda_method(Closure , Object , Stream , CancellationToken )
   at SpanJson.JsonSerializer.NonGeneric.Inner`2.InnerSerializeAsync(Object input, Stream stream, CancellationToken cancellationToken) in C:\projects\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 120
   at BeetleX.FastHttpApi.JsonResult.Write(PipeStream stream, HttpResponse response)
   at BeetleX.FastHttpApi.HttpResponse.OnWrite(PipeStream stream)
   at BeetleX.FastHttpApi.HttpResponse.BeetleX.FastHttpApi.IDataResponse.Write(PipeStream stream)
```
customer submitted a question and could not get more detailed information

**Comment by Tornhoof** [comment]
It's impossible to help you If you can't provide more information than that.

**Comment by hez2010** [comment]
I got the same problem. And actually there were 27 inner exceptions:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Inner`3' threw an exception.
  Source=SpanJson
  StackTrace:
   at SpanJson.JsonSerializer.Generic.Inner`3.InnerDeserialize(ReadOnlySpan`1& input) in C:\Users\hez20\Desktop\SpanJson\SpanJson\JsonSerializer.Generics.cs:line 122
   at SpanJson.JsonSerializer.Generic.Utf8.Deserialize[T,TResolver](Byte[] input) in C:\Users\hez20\Desktop\SpanJson\SpanJson\JsonSerializer.Generics.cs:line 462
   at SpanJson.JsonSerializer.Generic.Utf8.Deserialize[T](Byte[] input) in C:\Users\hez20\Desktop\SpanJson\SpanJson\JsonSerializer.Generics.cs:line 449
   at JsonTest.Program.Main(String[] args) in C:\Users\hez20\Desktop\JsonTest\Program.cs:line 80

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 3:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 4:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 5:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 6:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ArrayFormatter`3' threw an exception.

Inner Exception 7:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 8:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 9:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 10:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 11:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 12:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 13:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 14:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 15:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 16:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 17:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 18:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 19:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 20:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 21:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 22:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.EnumerableFormatter`4' threw an exception.

Inner Exception 23:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 24:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 25:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 26:
TypeInitializationException: The type initializer for 'SpanJson.Formatters.ComplexClassFormatter`3' threw an exception.

Inner Exception 27:
ArgumentException: Type 'System.Runtime.InteropServices.StructLayoutAttribute' does not have a default constructor
Parameter name: type

```

Test code:
```csharp
using System;
using System.Text;

namespace JsonTest
{
    public class ProducerOptions
    {
        public string Queue { get; set; } = string.Empty;
        public bool Durable { get; set; } = true;
        public bool Exclusive { get; set; } = false;
        public bool AutoDelete { get; set; } = false;
        public string Exchange { get; set; } = string.Empty;
        public string RoutingKey { get; set; } = string.Empty;
    }

    public class ConsumerOptions
    {
        public string Queue { get; set; } = string.Empty;
        public bool Durable { get; set; } = true;
        public bool AutoAck { get; set; } = false;
        public bool Exclusive { get; set; } = false;
        public string Exchange { get; set; } = string.Empty;
        public string RoutingKey { get; set; } = string.Empty;
        public EventHandler ProblemMaker { get; set; } // This is problem maker
    }
    class MessageQueueOptions
    {
        public string HostName { get; set; } = string.Empty;
        public string VirtualHost { get; set; } = "/";
        public int Port { get; set; } = 5672;
        public string UserName { get; set; } = "guest";
        public string Password { get; set; } = "guest";
        public ProducerOptions[]? Producers { get; set; }
        public ConsumerOptions[]? Consumers { get; set; }
    }
    class JudgeHostConfig
    {
        public MessageQueueOptions? MessageQueue { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var str = @"{
  ""MessageQueue"": {
    ""HostName"": ""localhost"",
    ""VirtualHost"": ""/"",
    ""Port"": 5672,
    ""UserName"": ""guest"",
    ""Password"": ""guest"",
    ""Producers"": [
      {
        ""Queue"": ""test"",
        ""Durable"": true,
        ""Exclusive"": false,
        ""AutoDelete"": false,
        ""Exchange"": ""test"",
        ""RoutingKey"": ""test""
      }
    ],
    ""Consumers"": [
      {
        ""Queue"": ""JudgeQueue"",
        ""Durable"": true,
        ""Exclusive"": false,
        ""AutoAck"": false,
        ""Exchange"": ""test"",
        ""RoutingKey"": ""test""
      }
    ]
  }
}";
            var result = SpanJson.JsonSerializer.Generic.Utf8.Deserialize<JudgeHostConfig>(Encoding.UTF8.GetBytes(str));
            return;
        }
    }
}

```

**Comment by Tornhoof** [comment]
SpanJson does not support serialization of delegates. You probably should ignore that property via ``IgnoreDataMember``.

**Comment by hez2010** [comment]
@Tornhoof I think you can serialize delegates as null directly.

**Comment by Tornhoof** [comment]
Yeah, that won't happen. The serialization library should not decide that. So the correct way for SpanJson is ``IgnoreDataMember``
