### ISSUE TITLE
System.ArgumentException: The output byte buffer is too small to contain the encoded data

### ISSUE THREAD

**Issue by dv00d00** [Tornhoof/SpanJson#38]
```
System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount)
   at System.Text.Encoding.GetBytes(ReadOnlySpan`1 chars, Span`1 bytes)
   at SpanJson.JsonWriter`1.WriteUtf8Name(ReadOnlySpan`1& value) in C:\projects\spanjson\SpanJson\JsonWriter.Utf8.cs:line 473
   at SpanJson.Formatters.DictionaryFormatter`4.Serialize(JsonWriter`1& writer, TDictionary value, Int32 nestingLimit) in C:\projects\spanjson\SpanJson\Formatters\DictionaryFormatter.cs:line 40
   at SpanJson.Formatters.BaseFormatter.SerializeRuntimeDecisionInternal[T,TSymbol,TResolver](JsonWriter`1& writer, T value, IJsonFormatter`2 formatter, Int32 nextNestingLimit) in C:\projects\spanjson\SpanJson\Formatters\BaseFormatter.cs:line 64
   at SpanJson.Formatters.DictionaryFormatter`4.Serialize(JsonWriter`1& writer, TDictionary value, Int32 nestingLimit) in C:\projects\spanjson\SpanJson\Formatters\DictionaryFormatter.cs:line 56
   at SpanJson.JsonSerializer.Generic.Inner`3.InnerSerializeAsync(T input, Stream stream, CancellationToken cancellationToken) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 75
   at SpanJson.JsonSerializer.Generic.Utf8.SerializeAsync[T,TResolver](T input, Stream stream, CancellationToken cancellationToken) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 454
   at SpanJson.JsonSerializer.Generic.Utf8.SerializeAsync[T](T input, Stream stream, CancellationToken cancellationToken) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 427
   at WebApplication5.Startup.<>c.<<Configure>b__1_1>d.MoveNext() in c:\users\dmytro.kushnir\source\repos\WebApplication5\WebApplication5\Program.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I've tried to reduce repro size, but it looks like 16k is some sort of magic number here. If keys are replaced by ascii chars, all is good for much larger cases.

Repro Code:

```
using System.Collections.Generic;

namespace WebApplication5
{
    public class Data
    {
        public static readonly Dictionary<string, object> Dictionary = new Dictionary<string, object>
        {
            ["Привет мир!0"] = new Dictionary<string, object>
            {
                ["Привет мир!0"] = new Dictionary<string, object>
                {
                    
                    ["Привет мир!1"] = 123,
                    
                    ["Привет мир!3"] = 123,
                    ["Привет мир!4"] = new Dictionary<string, object>
                    {
                        ["Привет мир!0"] = 123,
                        ["Привет мир!1"] = 123,
                        ["Привет мир!2"] = 123,
                       
                        ["Привет мир!4"] = 123,
                        ["Привет мир!5"] = 123
                    },
                    ["Привет мир!5"] = 123
                },
                ["Привет мир!1"] = 123,
                
                ["Привет мир!3"] = 123,
                
                ["Привет мир!5"] = 123
            },
            ["Привет мир!1"] = 123,
            ["Привет мир!2"] = new Dictionary<string, object>
            {
                ["Привет мир!0"] = 123,
                ["Привет мир!1"] = 123,
                ["Привет мир!2"] = 123,
                ["Привет мир!3"] = 123,
                ["Привет мир!4"] = new Dictionary<string, object>
                {
                    ["Привет мир!0"] = 123,
                    ["Привет мир!1"] = 123,
                    ["Привет мир!2"] = 123,
                    ["Привет мир!3"] = new Dictionary<string, object>
                    {
                        ["Привет мир!0"] = 123,
                        ["Привет мир!1"] = 123,
                        ["Привет мир!2"] = 123,
                        ["Привет мир!3"] = new Dictionary<string, object>
                        {
                            ["Привет мир!0"] = 123,
                            ["Привет мир!1"] = 123,
                            ["Привет мир!2"] = new Dictionary<string, object>
                            {
                                ["Привет мир!0"] = 123,
                                ["Привет мир!1"] = 123,
                                ["Привет мир!2"] = new Dictionary<string, object>
                                {
                                    ["Привет мир!0"] = 123,
                                    ["Привет мир!1"] = 123,
                                    ["Привет мир!2"] = 123,
                                    ["Привет мир!3"] = 123,
                                    ["Привет мир!4"] = new Dictionary<string, object>
                                    {
                                        ["Привет мир!0"] = 123,
                                        ["Привет мир!1"] = 123,
                                        ["Привет мир!2"] = 123,
                                        ["Привет мир!3"] = new Dictionary<string, object>
                                        {
                                            ["Привет мир!0"] = 123,
                                            ["Привет мир!1"] = 123,
                                            ["Привет мир!2"] = 123,
                                            ["Привет мир!3"] = new Dictionary<string, object>
                                            {
                                                ["Привет мир!0"] = 123,
                                                ["Привет мир!1"] = 123,
                                                ["Привет мир!2"] = new Dictionary<string, object>
                                                {
                                                    ["Привет мир!0"] = 123,
                                                    ["Привет мир!1"] = 123,
                                                    ["Привет мир!2"] = new Dictionary<string, object>
                                                    {
                                                        ["Привет мир!0"] = 123,
                                                        ["Привет мир!1"] = 123,
                                                        ["Привет мир!2"] = 123,
                                                        ["Привет мир!3"] = 123,
                                                        ["Привет мир!4"] = new Dictionary<string, object>
                                                        {
                                                            ["Привет мир!0"] = 123,
                                                            ["Привет мир!1"] = 123,
                                                            ["Привет мир!2"] = 123,
                                                            ["Привет мир!3"] = new Dictionary<string, object>
                                                            {
                                                                ["Привет мир!0"] = 123,
                                                                ["Привет мир!1"] = 123,
                                                                ["Привет мир!2"] = 123,
                                                                ["Привет мир!3"] = new Dictionary<string, object>
                                                                {
                                                                    ["Привет мир!0"] = 123,
                                                                    ["Привет мир!1"] = 123,
                                                                    ["Привет мир!2"] = new Dictionary<string, object>
                                                                    {
                                                                        ["Привет мир!0"] = 123,
                                                                        ["Привет мир!1"] = 123,
                                                                        ["Привет мир!2"] = new Dictionary<string, object>
                                                                        {
                                                                            ["Привет мир!0"] = 123,
                                                                            ["Привет мир!1"] = 123,
                                                                            ["Привет мир!2"] = 123,
                                                                            ["Привет мир!3"] = 123,
                                                                            ["Привет мир!4"] = new Dictionary<string, object>
                                                                            {
                                                                                ["Привет мир!0"] = 123,
                                                                                ["Привет мир!1"] = 123,
                                                                                ["Привет мир!2"] = 123,
                                                                                ["Привет мир!3"] =
                                                                                    new Dictionary<string, object>
                                                                                    {
                                                                                        ["Привет мир!0"] = 123,
                                                                                        ["Привет мир!1"] = 123,
                                                                                        ["Привет мир!2"] = 123,
                                                                                        ["Привет мир!3"] =
                                                                                            new Dictionary<string,
                                                                                                object>
                                                                                            {
                                                                                                ["Привет мир!0"] = 123,
                                                                                                ["Привет мир!1"] = 123,
                                                                                                ["Привет мир!2"] =
                                                                                                    new Dictionary<
                                                                                                        string, object>
                                                                                                    {
                                                                                                        ["Привет мир!0"] = 123,
                                                                                                        ["Привет мир!1"] = 123,
                                                                                                        ["Привет мир!2"] = 123,
                                                                                                        ["Привет мир!3"] = 123,
                                                                                                        ["Привет мир!4"] =
                                                                                                            new
                                                                                                                Dictionary
                                                                                                                <string,
                                                                                                                    int>
                                                                                                                {
                                                                                                                    ["Привет мир!0"]
                                                                                                                        = 123,
                                                                                                                    ["Привет мир!1"]
                                                                                                                        = 123,
                                                                                                                    ["Привет мир!2"]
                                                                                                                        = 123,
                                                                                                                    ["Привет мир!3"]
                                                                                                                        = 123,
                                                                                                                    ["Привет мир!4"]
                                                                                                                        = 123,
                                                                                                                    ["Привет мир!5"]
                                                                                                                        = 123
                                                                                                                },
                                                                                                        ["Привет мир!5"] = 123
                                                                                                    },
                                                                                                ["Привет мир!3"] = 123,
                                                                                                ["Привет мир!4"] = 123,
                                                                                                ["Привет мир!5"] = 123
                                                                                            },
                                                                                        ["Привет мир!4"] = 123,
                                                                                        ["Привет мир!5"] = 123
                                                                                    },
                                                                                ["Привет мир!4"] = 123,
                                                                                ["Привет мир!5"] = 123
                                                                            },
                                                                            ["Привет мир!5"] = 123
                                                                        },
                                                                        ["Привет мир!3"] = 123,
                                                                        ["Привет мир!4"] = new Dictionary<string, int>
                                                                        {
                                                                            ["Привет мир!0"] = 123,
                                                                            ["Привет мир!1"] = 123,
                                                                            ["Привет мир!2"] = 123,
                                                                            ["Привет мир!3"] = 123,
                                                                            ["Привет мир!4"] = 123,
                                                                            ["Привет мир!5"] = 123
                                                                        },
                                                                        ["Привет мир!5"] = 123
                                                                    },
                                                                    ["Привет мир!3"] = 123,
                                                                    ["Привет мир!4"] = 123,
                                                                    ["Привет мир!5"] = 123
                                                                },
                                                                ["Привет мир!4"] = 123,
                                                                ["Привет мир!5"] = 123
                                                            },
                                                            ["Привет мир!4"] = 123,
                                                            ["Привет мир!5"] = 123
                                                        },
                                                        ["Привет мир!5"] = 123
                                                    },
                                                    ["Привет мир!3"] = 123,
                                                    ["Привет мир!4"] = new Dictionary<string, int>
                                                    {
                                                        ["Привет мир!0"] = 123,
                                                        ["Привет мир!1"] = 123,
                                                        ["Привет мир!2"] = 123,
                                                        ["Привет мир!3"] = 123,
                                                        ["Привет мир!4"] = 123,
                                                        ["Привет мир!5"] = 123
                                                    },
                                                    ["Привет мир!5"] = 123
                                                },
                                                ["Привет мир!3"] = 123,
                                                ["Привет мир!4"] = 123,
                                                ["Привет мир!5"] = 123
                                            },
                                            ["Привет мир!4"] = 123,
                                            ["Привет мир!5"] = 123
                                        },
                                        ["Привет мир!4"] = 123,
                                        ["Привет мир!5"] = 123
                                    },
                                    ["Привет мир!5"] = 123
                                },
                                ["Привет мир!3"] = 123,
                                ["Привет мир!4"] = new Dictionary<string, int>
                                {
                                    ["Привет мир!0"] = 123,
                                    ["Привет мир!1"] = 123,
                                    ["Привет мир!2"] = 123,
                                    ["Привет мир!3"] = 123,
                                    ["Привет мир!4"] = 123,
                                    ["Привет мир!5"] = 123
                                },
                                ["Привет мир!5"] = 123
                            },
                            ["Привет мир!3"] = 123,
                            ["Привет мир!4"] = 123,
                            ["Привет мир!5"] = 123
                        },
                        ["Привет мир!4"] = 123,
                        ["Привет мир!5"] = 123
                    },
                    ["Привет мир!4"] = 123,
                    ["Привет мир!5"] = 123
                },
                ["Привет мир!5"] = 123
            },
            ["Привет мир!3"] = 123,
            
            ["Привет мир!5"] = 123
        };
    }
}
```
Main.cs
```
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using SpanJson;

namespace WebApplication5
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) => WebHost.CreateDefaultBuilder(args).UseStartup<Startup>();
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Use(next => conext =>
            {
                if (conext.Request.Path == "/favicon.ico")
                {
                    conext.Response.StatusCode = (int) HttpStatusCode.NotFound;
                    return Task.CompletedTask;
                }
                else
                {
                    conext.Response.Headers.Remove("X-Powerd-By");
                    conext.Response.Headers.Remove("X-SourceFiles");
                    return next(conext);
                }
            });

            app.Run(async context =>
            {
                context.Response.ContentType = "application/json";
                await JsonSerializer.Generic.Utf8.SerializeAsync(Data.Dictionary, context.Response.Body);
            });
        }
    }
}

```

csproj

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="SpanJson" Version="1.0.5" />
  </ItemGroup>

</Project>

```

**Comment by dv00d00** [comment]
https://github.com/Tornhoof/SpanJson/blob/1b17092305048b5181b519b2329f0a3dfd7484da/SpanJson/JsonWriter.Utf8.cs#L474

this is probably the reason.

**Comment by Tornhoof** [comment]
Yes I think you're right,the dictionaryformatter is uing that to write the cyrilic attribute names and those are longer than one byte.
It's missing Encoding.Utf8.GetMaxBytes(value.Length)+3, just like for WriteUtf8String:
https://github.com/Tornhoof/SpanJson/blob/1b17092305048b5181b519b2329f0a3dfd7484da/SpanJson/JsonWriter.Utf8.cs#L270

**Comment by dv00d00** [comment]
I would like to help with that, btw could non-ASCII C# names cause issues?
Like:

```
    public class CrazyRussianDto
    {
        public string ПустьВсегдаБудетСолнце1 {get;set;} = "Пусть всегда будет мама!";
        public string ПустьВсегдаБудетСолнце470 {get;set;} = "Пусть всегда будет мама!";
    }
```

**Comment by dv00d00** [comment]
I've tested it with 470 fields and given up, worked without issues

**Comment by Tornhoof** [comment]
> I would like to help with that, btw could non-ASCII C# names cause issues?
No I don't think so.
There are tests against chinese property names, WriteUtf8Name is only used in Dictionary and Dynamic, for the normal serializer all the property names are precalculated (including double quote and separator), so they shouldn't pose problems, the deserialization routine should handle them just fine too as that one doesn't care about how many bytes there are it only compares integer values based on the bytes and  has a proper Length calculation:
https://github.com/Tornhoof/SpanJson/blob/9cb950c7eb522eda815dc8a4963c7e618689d86b/SpanJson/Helpers/MemberComparisonBuilder.cs#L99-L111

**Comment by Tornhoof** [comment]
I've pushed 1.0.6, that should include the fix.
