### ISSUE TITLE
Unable to deserialize from Gzip Stream

### ISSUE THREAD

**Issue by tamnm** [Tornhoof/SpanJson#60]
Hi @Tornhoof ,

When I tried to de-serialize from Gzip decompressed stream, I got this exception:
SpanJson.JsonParserException: Error Reading JSON data: 'ExpectedBeginObject' at position: '0'.

Could you please help to check?
Below is stack trace and the unit test.

```StackTrace
SpanJson.JsonParserException: Error Reading JSON data: 'ExpectedBeginObject' at position: '0'.
    at SpanJson.JsonReader`1.ThrowJsonParserException(ParserError error) in C:\projects\spanjson\SpanJson\JsonReader.cs:line 50
   at lambda_method(Closure , JsonReader`1& )
   at SpanJson.Formatters.ComplexClassFormatter`3.Deserialize(JsonReader`1& reader) in C:\projects\spanjson\SpanJson\Formatters\ComplexClassFormatter.cs:line 21
   at SpanJson.JsonSerializer.Generic.Inner`3.InnerDeserialize(ReadOnlySpan`1& input) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 124
   at SpanJson.JsonSerializer.Generic.Inner`3.InnerDeserialize(Memory`1 memory) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 169
   at SpanJson.JsonSerializer.Generic.Inner`3.InnerDeserializeAsync(Stream stream, CancellationToken cancellationToken) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 142
   at SpanJson.JsonSerializer.Generic.Utf8.DeserializeAsync[T,TResolver](Stream stream, CancellationToken cancellationToken) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 543
   at SpanJson.JsonSerializer.Generic.Utf8.DeserializeAsync[T](Stream stream, CancellationToken cancellationToken) in C:\projects\spanjson\SpanJson\JsonSerializer.Generics.cs:line 514
   at JsonSerializationTests.GzipStreamTests.Deserialize_From_GzipStream_Vs_Newtonsoft_Json() 
```
```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;

namespace JsonSerializationTests
{
    [TestClass]
    public class GzipStreamTests
    {
        [TestMethod]
        public async Task Serialize_To_GzipStream_And_Deserialize_From_GzipStream()
        {
            using (var stream = new MemoryStream())
            using (var compressedStream = new GZipStream(stream, CompressionLevel.Fastest, true))
            {
                await SpanJson.JsonSerializer.Generic.Utf8.SerializeAsync(new Msg {Body = "HelloWorld"}, compressedStream);

                stream.Seek(0, SeekOrigin.Begin);
                using(var decompressStream = new GZipStream(stream,CompressionMode.Decompress, true))
                {
                    var msg = await SpanJson.JsonSerializer.Generic.Utf8.DeserializeAsync<Msg>(decompressStream);
                    Assert.IsNotNull(msg?.Body);
                }
            }
        }

        [TestMethod]
        public async Task Deserialize_From_GzipStream_Vs_Newtonsoft_Json()
        {
            var x = new Msg {Body = "HelloWorld"};
            var jsonSerializer = new JsonSerializer();

            using (var stream = new MemoryStream())
            using (var compressedStream = new GZipStream(stream, CompressionLevel.Fastest, true))
            {
                using (var textWriter = new StreamWriter(compressedStream, Encoding.UTF8, 1024, true))
                {
                    jsonSerializer.Serialize(textWriter, x);
                }

                //test with newtonsoft.json
                stream.Seek(0, SeekOrigin.Begin);
                using(var decompressStream = new GZipStream(stream,CompressionMode.Decompress, true))
                {
                    using(var textReader = new StreamReader(decompressStream, Encoding.UTF8, false, 1024, true))
                    using (var reader = new JsonTextReader(textReader))
                    {
                        var msg = jsonSerializer.Deserialize<Msg>(reader);
                        Assert.IsNotNull(msg?.Body);
                    }
                }

                //test with SpanJson
                stream.Seek(0, SeekOrigin.Begin);
                using(var decompressStream = new GZipStream(stream,CompressionMode.Decompress, true))
                {
                    //The below line got Exception
                    var msg = await SpanJson.JsonSerializer.Generic.Utf8.DeserializeAsync<Msg>(decompressStream); 

                    Assert.IsNotNull(msg?.Body);
                }
            }
        }
    }

    public class Msg
    {
        public string Body { get; set; }
    }
}

```

**Comment by Tornhoof** [comment]
Thank your for reporting this issue, it happens because you keep the ``compressedStream`` open and ``GzipStream`` does not flush automatically, only on ``close/dispose``.
Either you close your using-block after the compression is done or you manually flush the compressedStream with ``await compressedStream.FlushAsync().ConfigureAwait(false);``
I guess JSON.NET flushes the data after the serialization is done.

**Comment by tamnm** [comment]
Hi @Tornhoof ,

JSON.NET able to de-serialize, When I tried to use TextReader to get json string out from `stream` it returned exactly what i was expected.
It means before this block. stream already have fully data. 
```C#
                stream.Seek(0, SeekOrigin.Begin);
                using(var decompressStream = new GZipStream(stream,CompressionMode.Decompress, true))
                {
                    //The below line got Exception
                    var msg = await SpanJson.JsonSerializer.Generic.Utf8.DeserializeAsync<Msg>(decompressStream); 

                    Assert.IsNotNull(msg?.Body);
                }
```

**Comment by tamnm** [comment]
Hi @Tornhoof ,
I Think this will interest you. When I tried to get byte out of compressed stream, I found a difference between byte[] from stream vs byte[] from `Encoding.UTF8.GetBytes("{\"Body\":\"HelloWorld\"}")`

```
239,187,191,123,34,66,111,100,121,34,58,34,72,101,108,108,111,87,111,114,108,100,34,125 <--- this is from compressed stream
            123,34,66,111,100,121,34,58,34,72,101,108,108,111,87,111,114,108,100,34,125 <--- this is from Encoding.UTF8.GetBytes("{\"Body\":\"HelloWorld\"}")
```

**Comment by Tornhoof** [comment]
Ok, that's two different things at play here
> It means before this block. stream already have fully data.

In your first test the stream.Data is not full, if you read the .Length property from stream it's 0xA, only after flush it's 0x25. As I said, JSON.NET apparently flushes the stream after it's done.

> StreamWriter(stream, new UTF8Encoding(false), 1024, true))

BOM is not allowed in JSON, see: https://tools.ietf.org/html/rfc7159#section-8.1
For performance reasons I elected not to check for the BOM

**Comment by tamnm** [comment]
It make sense.
Thank for your explanation.
